on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Python
        uses: actions/setup-python@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: python -m build

      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@v1.8.14
