on:
  push:
    branches:
      - main
  workflow_dispatch:

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: commitlint
          pull-request-title-pattern: 'chore: release v${version}'
          pull-request-header: 'Release PR'
          changelog-types: >
            [
              {"type":"fix","section":"Bug Fixes"},
              {"type":"feat","section":"Features"}
            ]
          extra-files: >
            [
              "src/commitlint/__version__.py"
            ]

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Python
        uses: actions/setup-python@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: python -m build

      # Commented for now
      # - name: Publish package
      #   if: ${{ steps.release.outputs.release_created }}
      #   uses: pypa/gh-action-pypi-publish@v1.8.14
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
